version: '3'
services: 
    nginx:
        restart: always
        image: nginx
        volumes: 
            - /Users/chf_01/Desktop/MYPROJECT/vuedemo/nginx.conf:/etc/nginx/nginx.conf
            - /Users/chf_01/Desktop/MYPROJECT/vuedemo/dist:/usr/local/nginx/html
        ports:
            - '8080:8080'
        privileged: true